{% set version = "1.1.1" %}

package:
  name: fs-s3fs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fs-s3fs/fs-s3fs-{{ version }}.tar.gz
  sha256: b57f8c7664460ff7b451b4b44ca2ea9623a374d74e1284c2d5e6df499dc7976c

build:
  number: 4
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - boto3 >=1.9,<2
    - fs >=2.4,<3
    - six
    - enum34  # [py2k]

test:
  imports:
    - fs_s3fs

about:
  home: http://fs-s3fs.readthedocs.io/en/stable
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Amazon S3 filesystem for PyFilesystem2
  description: "Amazon S3 filesystem implementation for PyFilesystem2"
  doc_url: http://fs-s3fs.readthedocs.io/en/stable
  dev_url: https://github.com/PyFilesystem/s3fs

extra:
  recipe-maintainers: 
    - notestaff
    - willmcgugan
