appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WvXbKbouuIaEMd4Zlw+oijx82h08IWN6WPyWuOP8wl/JUrviPgtTksJ7afRjf4YyPqTzQPIST456PR8orVAQkK2L6uvJADB3KZhNnJMQmROd8KmnHnw2KB3d7de5bZuTLNm46cJTzQw+ntwo0vdARSSa37IvETt+fRxtksu96BM/GQeomQLQBhlCIhqebilonwEcnTycuqZPxFuGyX0kjplfEAmTwGeSXg0Hz1G0+46IP6ZLN9pJo2fs8P1kJxK1Ogd00o8FzTsd3PGz39OtM0/NM/uFL3T+MutZ4Iee9AFpirB1Rix9Jy4Uu3hvcNOFjsdlfzm27XGmi6MRg+Hnx3b+CKofucWHQzhh6kS+VX0bOcp0syX8h3cEjpx4hzDv3muhfBvqxSuiU3eG7k4gMIvqfuIkHnEgU+Hwoa/Xv6SnzG1lhwIcWX0wXIyrde1WMdkFNzLi4d7pQc0XFt/s0GxvKXHxD1JtleYI42iNvgfr5Rz12tXSGNI1aCueQsZZAUuKo9MQ45hr7PB9sQfNHeWklOkVQP1ryvSP99AlES78JVFd7UNdvkv4xGx06561kerrvW99wAOLrIJZM6CSdxYLZrRtG8bUn04pl6uRGIuuqLG79HUc6x9SAScUqen2SAdQ5iRCYRWm5NrQW1MI6VwmI15i3PJeiNp+Ll1SCqo=}
